### ISSUE TITLE
VertxTestContext#succeeding() should create a checkpoint

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-junit5#5]
that is flagged when succeeding is completed and the next handler has been called (so the next handler has the opportunity to create a new checkpoint).

Similar for the `failing()` method.

**Comment by vietj** [comment]
I can see that a succeeding handler can call `VertxTestContext#completeNow()` to achieve it, however I don't see that practical to use when there are multiple succeeding handlers that will need to synchronize to call completeNow

**Comment by jponge** [comment]
Related to #4 as well.

**Comment by jponge** [comment]
There is a correctness issue in this design, as illustrated by #31.

While making `succeeding` and `failing` helpers create checkpoints helps in reducing the code to be written, the main problem with that design is that the `VertxTestContext` doesn't know _a-priori_ how many checkpoints will be created (we'd need static analysis of the code for that)

The correct way to use checkpoints is to create them on the test main thread and not in callbacks, and this is what we have in examples / documentation. By doing so, when `awaitCompletion` is reached from the test runner thread, then we can await for all checkpoints.

Now when checkpoints are being created from Vert.x event handlers (and thus not on the same thread) then checkpoints get added on the fly. In the case of a `succeeding(handler)` helper, then:

1. a new checkpoint is being created, the test context becomes aware of it,
2. if the `AsyncResult` is correct, then that checkpoint gets flagged,
3. because that checkpoint is potentially the single one (as in #31) then all checkpoints in the test context have completed, and the test completes,
4. all subsequent asynchronous events will be eventually executed, but since the test context has already failed then no errors are being reported.

Conclusion: we need to stop creating checkpoints in these asynchronous helpers, and we need explicit cooperation to complete asynchronous test contexts in test and lifecycle methods (either via `completeNow()` on simples cases, or with checkpoints).

Note: since we have timeouts no operation will block forever, so badly written tests will get noticed.

/cc @dadoonet

**Comment by vietj** [comment]
yes, checkpoints have to be created in time.

In Vert Unit the following rules are used:

1/ the integration creates a checkpoint that is completed when the `@Test` method has been invoked
2/ the test pass when all the checkpoints have been completed or there is at least one failure
3/ it is possible to create new checkpoints as long as the test is not completed
